from __future__ import annotations

import unittest

from finley.models.run_cell_baseline import (
    apply_feature_scaler,
    build_design_matrix,
    compute_metrics,
    filter_rows_for_target,
    fit_feature_scaler,
    get_default_alpha_sweep_specs,
    get_feature_count,
    list_sessions,
    resolve_feature_groups,
    run_alpha_sweep,
    run_feature_ablations,
    run_leave_one_session_out,
    split_by_session,
)


class RunCellBaselineTests(unittest.TestCase):
    def test_split_by_session_holds_out_latest_by_default(self) -> None:
        rows = [
            {"session": 3, "task_environment": "TrackA", "task_exposure": 1, "task_experimentday": 7, "pos_rows": 10, "epoch_duration_sec": 9.0, "mean_speed": 1.0, "std_speed": 0.2, "max_speed": 2.0, "mean_accel": 0.1, "std_accel": 0.05, "mean_abs_accel": 0.1, "max_abs_accel": 0.2, "speed_q25": 0.5, "speed_q50": 1.0, "speed_q75": 1.5, "moving_fraction": 0.5, "fast_fraction": 0.1, "path_length": 20.0, "step_length_mean": 2.0, "step_length_max": 3.0, "x_range": 10.0, "y_range": 5.0, "rawpos_rows": 10, "spike_tetrode_count": 1, "spike_cell_count": 2, "spike_event_rows_epoch": 5, "tetrode": 1, "depth": 100, "spikewidth": 8.0, "num_spikes": 2, "log_num_spikes": 1.0},
            {"session": 4, "task_environment": "TrackB", "task_exposure": 2, "task_experimentday": 8, "pos_rows": 12, "epoch_duration_sec": 10.0, "mean_speed": 1.5, "std_speed": 0.3, "max_speed": 2.5, "mean_accel": 0.2, "std_accel": 0.07, "mean_abs_accel": 0.2, "max_abs_accel": 0.4, "speed_q25": 1.0, "speed_q50": 1.5, "speed_q75": 2.0, "moving_fraction": 0.6, "fast_fraction": 0.2, "path_length": 22.0, "step_length_mean": 2.2, "step_length_max": 3.2, "x_range": 12.0, "y_range": 6.0, "rawpos_rows": 12, "spike_tetrode_count": 2, "spike_cell_count": 3, "spike_event_rows_epoch": 9, "tetrode": 2, "depth": 110, "spikewidth": 9.0, "num_spikes": 3, "log_num_spikes": 1.3},
        ]
        split = split_by_session(rows)
        self.assertEqual(split.held_out_session, 4)
        self.assertEqual(len(split.train_rows), 1)
        self.assertEqual(len(split.test_rows), 1)

    def test_build_design_matrix_shapes(self) -> None:
        rows = [
            {
                "session": 3,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 7,
                "pos_rows": 10,
                "epoch_duration_sec": 9.0,
                "mean_speed": 1.0,
                "std_speed": 0.2,
                "max_speed": 2.0,
                "mean_accel": 0.1,
                "std_accel": 0.05,
                "mean_abs_accel": 0.1,
                "max_abs_accel": 0.2,
                "speed_q25": 0.5,
                "speed_q50": 1.0,
                "speed_q75": 1.5,
                "moving_fraction": 0.5,
                "fast_fraction": 0.1,
                "path_length": 20.0,
                "step_length_mean": 2.0,
                "step_length_max": 3.0,
                "x_range": 10.0,
                "y_range": 5.0,
                "rawpos_rows": 10,
                "spike_tetrode_count": 1,
                "spike_cell_count": 2,
                "spike_event_rows_epoch": 5,
                "tetrode": 1,
                "depth": 100,
                "spikewidth": 8.0,
                "num_spikes": 2,
                "log_num_spikes": 1.0,
            }
        ]
        x, y = build_design_matrix(rows, target_column="log_num_spikes")
        self.assertEqual(len(x), 1)
        self.assertEqual(len(x[0]), 31)
        self.assertEqual(len(y), 1)

    def test_build_design_matrix_uses_selected_feature_groups(self) -> None:
        rows = [
            {
                "session": 3,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 7,
                "pos_rows": 10,
                "epoch_duration_sec": 9.0,
                "mean_speed": 1.0,
                "std_speed": 0.2,
                "max_speed": 2.0,
                "mean_accel": 0.1,
                "std_accel": 0.05,
                "mean_abs_accel": 0.1,
                "max_abs_accel": 0.2,
                "speed_q25": 0.5,
                "speed_q50": 1.0,
                "speed_q75": 1.5,
                "moving_fraction": 0.5,
                "fast_fraction": 0.1,
                "path_length": 20.0,
                "step_length_mean": 2.0,
                "step_length_max": 3.0,
                "x_range": 10.0,
                "y_range": 5.0,
                "rawpos_rows": 10,
                "spike_tetrode_count": 1,
                "spike_cell_count": 2,
                "spike_event_rows_epoch": 5,
                "tetrode": 1,
                "depth": 100,
                "spikewidth": 8.0,
                "num_spikes": 2,
                "log_num_spikes": 1.0,
            }
        ]
        x, _ = build_design_matrix(
            rows,
            target_column="log_num_spikes",
            feature_groups=["task_context", "cell_metadata"],
        )
        self.assertEqual(len(x[0]), 8)

    def test_build_design_matrix_rejects_missing_target_values(self) -> None:
        rows = [
            {
                "session": 3,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 7,
                "pos_rows": 10,
                "epoch_duration_sec": 9.0,
                "mean_speed": 1.0,
                "std_speed": 0.2,
                "max_speed": 2.0,
                "mean_accel": 0.1,
                "std_accel": 0.05,
                "mean_abs_accel": 0.1,
                "max_abs_accel": 0.2,
                "speed_q25": 0.5,
                "speed_q50": 1.0,
                "speed_q75": 1.5,
                "moving_fraction": 0.5,
                "fast_fraction": 0.1,
                "path_length": 20.0,
                "step_length_mean": 2.0,
                "step_length_max": 3.0,
                "x_range": 10.0,
                "y_range": 5.0,
                "rawpos_rows": 10,
                "spike_tetrode_count": 1,
                "spike_cell_count": 2,
                "spike_event_rows_epoch": 5,
                "tetrode": 1,
                "depth": 100,
                "spikewidth": 8.0,
                "num_spikes": 2,
                "log_firing_rate_hz": None,
            }
        ]
        with self.assertRaises(ValueError):
            build_design_matrix(rows, target_column="log_firing_rate_hz")

    def test_filter_rows_for_target_drops_missing_values(self) -> None:
        rows = [{"log_firing_rate_hz": 1.0}, {"log_firing_rate_hz": None}]
        filtered_rows, dropped_count = filter_rows_for_target(rows, "log_firing_rate_hz")
        self.assertEqual(len(filtered_rows), 1)
        self.assertEqual(dropped_count, 1)

    def test_compute_metrics_filters_missing_target_rows(self) -> None:
        train_rows = [
            {
                "session": 3,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 7,
                "pos_rows": 10,
                "epoch_duration_sec": 9.0,
                "mean_speed": 1.0,
                "std_speed": 0.2,
                "max_speed": 2.0,
                "mean_accel": 0.1,
                "std_accel": 0.05,
                "mean_abs_accel": 0.1,
                "max_abs_accel": 0.2,
                "speed_q25": 0.5,
                "speed_q50": 1.0,
                "speed_q75": 1.5,
                "moving_fraction": 0.5,
                "fast_fraction": 0.1,
                "path_length": 20.0,
                "step_length_mean": 2.0,
                "step_length_max": 3.0,
                "x_range": 10.0,
                "y_range": 5.0,
                "rawpos_rows": 10,
                "spike_tetrode_count": 1,
                "spike_cell_count": 2,
                "spike_event_rows_epoch": 5,
                "tetrode": 1,
                "depth": 100,
                "spikewidth": 8.0,
                "num_spikes": 2,
                "log_firing_rate_hz": 1.0,
            },
            {
                "session": 3,
                "task_environment": "TrackB",
                "task_exposure": 1,
                "task_experimentday": 7,
                "pos_rows": 10,
                "epoch_duration_sec": None,
                "mean_speed": 1.2,
                "std_speed": 0.2,
                "max_speed": 2.2,
                "mean_accel": 0.15,
                "std_accel": 0.04,
                "mean_abs_accel": 0.15,
                "max_abs_accel": 0.3,
                "speed_q25": 0.6,
                "speed_q50": 1.1,
                "speed_q75": 1.6,
                "moving_fraction": 0.4,
                "fast_fraction": 0.1,
                "path_length": 18.0,
                "step_length_mean": 1.8,
                "step_length_max": 2.8,
                "x_range": 9.0,
                "y_range": 4.0,
                "rawpos_rows": 9,
                "spike_tetrode_count": 1,
                "spike_cell_count": 2,
                "spike_event_rows_epoch": 4,
                "tetrode": 1,
                "depth": 90,
                "spikewidth": 7.5,
                "num_spikes": 1,
                "log_firing_rate_hz": None,
            },
        ]
        test_rows = [
            {
                "session": 4,
                "task_environment": "TrackA",
                "task_exposure": 2,
                "task_experimentday": 8,
                "pos_rows": 12,
                "epoch_duration_sec": 10.0,
                "mean_speed": 1.5,
                "std_speed": 0.3,
                "max_speed": 2.5,
                "mean_accel": 0.2,
                "std_accel": 0.07,
                "mean_abs_accel": 0.2,
                "max_abs_accel": 0.4,
                "speed_q25": 1.0,
                "speed_q50": 1.5,
                "speed_q75": 2.0,
                "moving_fraction": 0.6,
                "fast_fraction": 0.2,
                "path_length": 22.0,
                "step_length_mean": 2.2,
                "step_length_max": 3.2,
                "x_range": 12.0,
                "y_range": 6.0,
                "rawpos_rows": 12,
                "spike_tetrode_count": 2,
                "spike_cell_count": 3,
                "spike_event_rows_epoch": 9,
                "tetrode": 2,
                "depth": 110,
                "spikewidth": 9.0,
                "num_spikes": 3,
                "log_firing_rate_hz": 1.2,
            }
        ]
        metrics = compute_metrics(
            train_rows,
            test_rows,
            held_out_session=4,
            target_column="log_firing_rate_hz",
        )
        self.assertEqual(metrics.train_count, 1)
        self.assertEqual(metrics.test_count, 1)
        self.assertEqual(metrics.dropped_train_count, 1)
        self.assertEqual(metrics.dropped_test_count, 0)
        self.assertEqual(metrics.feature_count, 31)
        self.assertEqual(
            metrics.feature_groups,
            ["task_context", "movement_summaries", "population_context", "cell_metadata"],
        )

    def test_resolve_feature_groups_rejects_unknown_group(self) -> None:
        with self.assertRaises(ValueError):
            resolve_feature_groups(["bogus"])

    def test_get_feature_count_matches_group_selection(self) -> None:
        self.assertEqual(get_feature_count(["task_context"]), 5)
        self.assertEqual(get_feature_count(["task_context", "cell_metadata"]), 8)
        self.assertEqual(get_feature_count(["movement_summaries"]), 20)

    def test_run_feature_ablations_returns_standard_suite(self) -> None:
        rows = [
            {
                "session": 3,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 7,
                "pos_rows": 10,
                "epoch_duration_sec": 9.0,
                "mean_speed": 1.0,
                "std_speed": 0.2,
                "max_speed": 2.0,
                "speed_q25": 0.5,
                "speed_q50": 1.0,
                "speed_q75": 1.5,
                "moving_fraction": 0.5,
                "fast_fraction": 0.1,
                "path_length": 20.0,
                "step_length_mean": 2.0,
                "step_length_max": 3.0,
                "x_range": 10.0,
                "y_range": 5.0,
                "rawpos_rows": 10,
                "spike_tetrode_count": 1,
                "spike_cell_count": 2,
                "spike_event_rows_epoch": 5,
                "tetrode": 1,
                "depth": 100,
                "spikewidth": 8.0,
                "num_spikes": 2,
                "log_num_spikes": 1.0,
            },
            {
                "session": 3,
                "task_environment": "TrackB",
                "task_exposure": 2,
                "task_experimentday": 7,
                "pos_rows": 11,
                "epoch_duration_sec": 9.5,
                "mean_speed": 1.2,
                "std_speed": 0.3,
                "max_speed": 2.1,
                "speed_q25": 0.6,
                "speed_q50": 1.1,
                "speed_q75": 1.6,
                "moving_fraction": 0.6,
                "fast_fraction": 0.2,
                "path_length": 19.0,
                "step_length_mean": 1.9,
                "step_length_max": 2.9,
                "x_range": 9.0,
                "y_range": 4.0,
                "rawpos_rows": 11,
                "spike_tetrode_count": 1,
                "spike_cell_count": 3,
                "spike_event_rows_epoch": 6,
                "tetrode": 2,
                "depth": 105,
                "spikewidth": 8.5,
                "num_spikes": 3,
                "log_num_spikes": 1.3,
            },
            {
                "session": 4,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 8,
                "pos_rows": 12,
                "epoch_duration_sec": 10.0,
                "mean_speed": 1.5,
                "std_speed": 0.3,
                "max_speed": 2.5,
                "speed_q25": 1.0,
                "speed_q50": 1.5,
                "speed_q75": 2.0,
                "moving_fraction": 0.6,
                "fast_fraction": 0.2,
                "path_length": 22.0,
                "step_length_mean": 2.2,
                "step_length_max": 3.2,
                "x_range": 12.0,
                "y_range": 6.0,
                "rawpos_rows": 12,
                "spike_tetrode_count": 2,
                "spike_cell_count": 3,
                "spike_event_rows_epoch": 9,
                "tetrode": 2,
                "depth": 110,
                "spikewidth": 9.0,
                "num_spikes": 3,
                "log_num_spikes": 1.2,
            },
            {
                "session": 4,
                "task_environment": "TrackB",
                "task_exposure": 2,
                "task_experimentday": 8,
                "pos_rows": 13,
                "epoch_duration_sec": 10.5,
                "mean_speed": 1.6,
                "std_speed": 0.4,
                "max_speed": 2.6,
                "speed_q25": 1.1,
                "speed_q50": 1.6,
                "speed_q75": 2.1,
                "moving_fraction": 0.7,
                "fast_fraction": 0.2,
                "path_length": 23.0,
                "step_length_mean": 2.3,
                "step_length_max": 3.3,
                "x_range": 13.0,
                "y_range": 6.5,
                "rawpos_rows": 13,
                "spike_tetrode_count": 2,
                "spike_cell_count": 4,
                "spike_event_rows_epoch": 10,
                "tetrode": 3,
                "depth": 111,
                "spikewidth": 9.1,
                "num_spikes": 4,
                "log_num_spikes": 1.4,
            },
        ]
        results = run_feature_ablations(rows, target_column="log_num_spikes", held_out_session=4)
        self.assertEqual(len(results), 9)
        self.assertEqual(results[0].name, "all")
        self.assertEqual(results[1].name, "task_context")
        self.assertEqual(results[-1].name, "all_minus_cell_metadata")

    def test_get_default_alpha_sweep_specs_returns_shortlist(self) -> None:
        specs = get_default_alpha_sweep_specs()
        self.assertEqual(len(specs), 5)
        self.assertEqual(specs[0][0], "movement_summaries")

    def test_list_sessions_returns_sorted_sessions(self) -> None:
        rows = [{"session": 10}, {"session": 3}, {"session": 4}, {"session": 3}]
        self.assertEqual(list_sessions(rows), [3, 4, 10])

    def test_run_alpha_sweep_returns_rows_for_each_alpha_and_spec(self) -> None:
        rows = [
            {
                "session": 3,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 7,
                "pos_rows": 10,
                "epoch_duration_sec": 9.0,
                "mean_speed": 1.0,
                "std_speed": 0.2,
                "max_speed": 2.0,
                "speed_q25": 0.5,
                "speed_q50": 1.0,
                "speed_q75": 1.5,
                "moving_fraction": 0.5,
                "fast_fraction": 0.1,
                "path_length": 20.0,
                "step_length_mean": 2.0,
                "step_length_max": 3.0,
                "x_range": 10.0,
                "y_range": 5.0,
                "rawpos_rows": 10,
                "spike_tetrode_count": 1,
                "spike_cell_count": 2,
                "spike_event_rows_epoch": 5,
                "tetrode": 1,
                "depth": 100,
                "spikewidth": 8.0,
                "num_spikes": 2,
                "log_num_spikes": 1.0,
            },
            {
                "session": 3,
                "task_environment": "TrackB",
                "task_exposure": 2,
                "task_experimentday": 7,
                "pos_rows": 11,
                "epoch_duration_sec": 9.5,
                "mean_speed": 1.2,
                "std_speed": 0.3,
                "max_speed": 2.1,
                "speed_q25": 0.6,
                "speed_q50": 1.1,
                "speed_q75": 1.6,
                "moving_fraction": 0.6,
                "fast_fraction": 0.2,
                "path_length": 19.0,
                "step_length_mean": 1.9,
                "step_length_max": 2.9,
                "x_range": 9.0,
                "y_range": 4.0,
                "rawpos_rows": 11,
                "spike_tetrode_count": 1,
                "spike_cell_count": 3,
                "spike_event_rows_epoch": 6,
                "tetrode": 2,
                "depth": 105,
                "spikewidth": 8.5,
                "num_spikes": 3,
                "log_num_spikes": 1.3,
            },
            {
                "session": 4,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 8,
                "pos_rows": 12,
                "epoch_duration_sec": 10.0,
                "mean_speed": 1.5,
                "std_speed": 0.3,
                "max_speed": 2.5,
                "speed_q25": 1.0,
                "speed_q50": 1.5,
                "speed_q75": 2.0,
                "moving_fraction": 0.6,
                "fast_fraction": 0.2,
                "path_length": 22.0,
                "step_length_mean": 2.2,
                "step_length_max": 3.2,
                "x_range": 12.0,
                "y_range": 6.0,
                "rawpos_rows": 12,
                "spike_tetrode_count": 2,
                "spike_cell_count": 3,
                "spike_event_rows_epoch": 9,
                "tetrode": 2,
                "depth": 110,
                "spikewidth": 9.0,
                "num_spikes": 3,
                "log_num_spikes": 1.2,
            },
            {
                "session": 4,
                "task_environment": "TrackB",
                "task_exposure": 2,
                "task_experimentday": 8,
                "pos_rows": 13,
                "epoch_duration_sec": 10.5,
                "mean_speed": 1.6,
                "std_speed": 0.4,
                "max_speed": 2.6,
                "speed_q25": 1.1,
                "speed_q50": 1.6,
                "speed_q75": 2.1,
                "moving_fraction": 0.7,
                "fast_fraction": 0.2,
                "path_length": 23.0,
                "step_length_mean": 2.3,
                "step_length_max": 3.3,
                "x_range": 13.0,
                "y_range": 6.5,
                "rawpos_rows": 13,
                "spike_tetrode_count": 2,
                "spike_cell_count": 4,
                "spike_event_rows_epoch": 10,
                "tetrode": 3,
                "depth": 111,
                "spikewidth": 9.1,
                "num_spikes": 4,
                "log_num_spikes": 1.4,
            },
        ]
        results = run_alpha_sweep(
            rows,
            target_column="log_num_spikes",
            ridge_alphas=[1.0, 10.0],
            held_out_session=4,
            feature_group_specs=[
                ("movement_summaries", ["movement_summaries"]),
                ("population_context", ["population_context"]),
            ],
        )
        self.assertEqual(len(results), 4)
        self.assertEqual(results[0].ridge_alpha, 1.0)
        self.assertEqual(results[1].ridge_alpha, 10.0)
        self.assertEqual(results[2].name, "population_context")

    def test_run_leave_one_session_out_returns_summary(self) -> None:
        rows = [
            {
                "session": 3,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 7,
                "pos_rows": 10,
                "epoch_duration_sec": 9.0,
                "mean_speed": 1.0,
                "std_speed": 0.2,
                "max_speed": 2.0,
                "mean_accel": 0.1,
                "std_accel": 0.05,
                "mean_abs_accel": 0.1,
                "max_abs_accel": 0.2,
                "speed_q25": 0.5,
                "speed_q50": 1.0,
                "speed_q75": 1.5,
                "moving_fraction": 0.5,
                "fast_fraction": 0.1,
                "path_length": 20.0,
                "step_length_mean": 2.0,
                "step_length_max": 3.0,
                "x_range": 10.0,
                "y_range": 5.0,
                "rawpos_rows": 10,
                "spike_tetrode_count": 1,
                "spike_cell_count": 2,
                "spike_event_rows_epoch": 5,
                "tetrode": 1,
                "depth": 100,
                "spikewidth": 8.0,
                "num_spikes": 2,
                "log_num_spikes": 1.0,
            },
            {
                "session": 3,
                "task_environment": "TrackB",
                "task_exposure": 2,
                "task_experimentday": 7,
                "pos_rows": 11,
                "epoch_duration_sec": 9.5,
                "mean_speed": 1.2,
                "std_speed": 0.3,
                "max_speed": 2.1,
                "mean_accel": 0.12,
                "std_accel": 0.04,
                "mean_abs_accel": 0.12,
                "max_abs_accel": 0.22,
                "speed_q25": 0.6,
                "speed_q50": 1.1,
                "speed_q75": 1.6,
                "moving_fraction": 0.6,
                "fast_fraction": 0.2,
                "path_length": 19.0,
                "step_length_mean": 1.9,
                "step_length_max": 2.9,
                "x_range": 9.0,
                "y_range": 4.0,
                "rawpos_rows": 11,
                "spike_tetrode_count": 1,
                "spike_cell_count": 3,
                "spike_event_rows_epoch": 6,
                "tetrode": 2,
                "depth": 105,
                "spikewidth": 8.5,
                "num_spikes": 3,
                "log_num_spikes": 1.3,
            },
            {
                "session": 4,
                "task_environment": "TrackA",
                "task_exposure": 1,
                "task_experimentday": 8,
                "pos_rows": 12,
                "epoch_duration_sec": 10.0,
                "mean_speed": 1.5,
                "std_speed": 0.3,
                "max_speed": 2.5,
                "mean_accel": 0.2,
                "std_accel": 0.07,
                "mean_abs_accel": 0.2,
                "max_abs_accel": 0.4,
                "speed_q25": 1.0,
                "speed_q50": 1.5,
                "speed_q75": 2.0,
                "moving_fraction": 0.6,
                "fast_fraction": 0.2,
                "path_length": 22.0,
                "step_length_mean": 2.2,
                "step_length_max": 3.2,
                "x_range": 12.0,
                "y_range": 6.0,
                "rawpos_rows": 12,
                "spike_tetrode_count": 2,
                "spike_cell_count": 3,
                "spike_event_rows_epoch": 9,
                "tetrode": 2,
                "depth": 110,
                "spikewidth": 9.0,
                "num_spikes": 3,
                "log_num_spikes": 1.2,
            },
            {
                "session": 4,
                "task_environment": "TrackB",
                "task_exposure": 2,
                "task_experimentday": 8,
                "pos_rows": 13,
                "epoch_duration_sec": 10.5,
                "mean_speed": 1.6,
                "std_speed": 0.4,
                "max_speed": 2.6,
                "mean_accel": 0.22,
                "std_accel": 0.08,
                "mean_abs_accel": 0.22,
                "max_abs_accel": 0.42,
                "speed_q25": 1.1,
                "speed_q50": 1.6,
                "speed_q75": 2.1,
                "moving_fraction": 0.7,
                "fast_fraction": 0.2,
                "path_length": 23.0,
                "step_length_mean": 2.3,
                "step_length_max": 3.3,
                "x_range": 13.0,
                "y_range": 6.5,
                "rawpos_rows": 13,
                "spike_tetrode_count": 2,
                "spike_cell_count": 4,
                "spike_event_rows_epoch": 10,
                "tetrode": 3,
                "depth": 111,
                "spikewidth": 9.1,
                "num_spikes": 4,
                "log_num_spikes": 1.4,
            },
        ]
        metrics_by_session, summary = run_leave_one_session_out(
            rows,
            target_column="log_num_spikes",
            ridge_alpha=100.0,
            feature_groups=["movement_summaries"],
        )
        self.assertEqual(len(metrics_by_session), 2)
        self.assertEqual(summary.session_count, 2)
        self.assertEqual(summary.feature_groups, ["movement_summaries"])

    def test_feature_scaler_preserves_intercept_and_scales_columns(self) -> None:
        x = [
            [1.0, 10.0, 100.0],
            [1.0, 20.0, 300.0],
        ]
        scaler = fit_feature_scaler(x)
        transformed = apply_feature_scaler(x, scaler)
        self.assertEqual(transformed[0][0], 1.0)
        self.assertEqual(transformed[1][0], 1.0)
        self.assertAlmostEqual(sum(row[1] for row in transformed) / 2, 0.0)


if __name__ == "__main__":
    unittest.main()
